# Generated by Django 3.1 on 2021-03-22 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='team.png', upload_to='Blogger_profile/')),
                ('BloggerName', models.CharField(max_length=60, unique=True)),
                ('About', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('Accounttype', models.CharField(blank=True, choices=[('Affiliate-Blogs', 'Affiliate Blogs'), ('Books-Blogs', 'Books Blogs'), ('Business-Blogs', 'Business Blogs'), ('Car-Blogs', 'Car Blogs'), ('Corporate-Blog', 'Corporate Blog'), ('Case-Study-Blogs', 'Case Study Blogs'), ('Contests', 'Contests'), ('Controversial-Subjects', 'Controversial Subjects'), ('DIY-Blogs', 'DIY Blogs'), ('Debates', 'Debates'), ('Entertainment-Blogs', 'Entertainment Blogs'), ('Event-Summaries', 'Event Summaries'), ('Fashion-blogs', 'Fashion blogs'), ('Finance-Blogs', 'Finance Blogs'), ('Fitness-Blogs', 'Fitness Blogs'), ('Food-Blogs', 'Food Blogs'), ('Freelance-bloggers', 'Freelance bloggers'), ('Gaming-blogs', 'Gaming Blogs'), ('How-to-Blogs', 'How-to Blogs'), ('Inspirational-Blogs', 'Inspirational Blogs'), ('Interviews', 'Interviews'), ('Lifestyle-Blogs', 'Lifestyle Blogs'), ('Listicles', 'Listicles'), ('Movie-Blogs', 'Movie Blogs'), ('Music-Blogs', 'Music Blogs'), ('News-blogs', 'News Blogs'), ('Parenting-Blogs', 'Parenting Blogs'), ('Personal-Blogs', 'Personal Blogs'), ('Personal-Services-Blog', 'Personal Services Blog'), ('Pet-Blogs', 'Pet Blogs'), ('Podcast', 'Podcast'), ('Political-Blogs', 'Political Blogs'), ('Professional-Blogs', 'Professional Blogs'), ('Reviews', 'Reviews'), ('Surveys-and-Polls', 'Surveys and Polls'), ('Sports-Blogs', 'Sports Blogs'), ('Tutorials', 'Tutorials'), ('Travel-Blogs', 'Travel Blogs'), ('The-Counter-Culture-Blogs', 'The Counter-Culture Blogs'), ('Writing-Blogs', 'Writing Blogs'), ('Poetry', 'Poetry')], default='Personal-Blogs', max_length=100)),
                ('Meta_discription', models.CharField(blank=True, max_length=160, null=True)),
                ('Meta_keyworads', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook_url', models.URLField(blank=True, max_length=300)),
                ('instagram_url', models.URLField(blank=True, max_length=300)),
                ('youtube_url', models.URLField(blank=True, max_length=300)),
                ('twitter_url', models.URLField(blank=True, max_length=300)),
                ('snaptube_url', models.URLField(blank=True, max_length=300)),
                ('pinterest_url', models.URLField(blank=True, max_length=300)),
                ('tumblr_url', models.URLField(blank=True, max_length=300)),
                ('personal_websitelink', models.URLField(blank=True, max_length=300)),
                ('Founder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Founders', to=settings.AUTH_USER_MODEL)),
                ('Members', models.ManyToManyField(blank=True, related_name='bloggerMembers', to=settings.AUTH_USER_MODEL)),
                ('subscribers', models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
