# Generated by Django 3.1.7 on 2021-03-24 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bloggers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='Members',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='Meta_discription',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='Meta_keyworads',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='pinterest_url',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='snaptube_url',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='tumblr_url',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='youtube_url',
        ),
    ]
