# Generated by Django 3.1 on 2021-03-22 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='pfile',
            new_name='profile',
        ),
    ]
