# Generated by Django 3.1 on 2021-03-22 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bloggers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blogtiltle', models.CharField(max_length=60)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('Discription', models.CharField(blank=True, max_length=160, null=True)),
                ('image', models.ImageField(blank=True, default='Blog.png', upload_to='BlogThumnailimg/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('UpBlog', models.TextField(blank=True, null=True)),
                ('ReadyToShow', models.BooleanField(default=True)),
                ('Conclusion', models.CharField(blank=True, max_length=400)),
                ('Meta_discription', models.CharField(blank=True, max_length=160, null=True)),
                ('Meta_keyworads', models.CharField(blank=True, max_length=200, null=True)),
                ('Authors', models.ManyToManyField(related_name='BlogMembers', to=settings.AUTH_USER_MODEL)),
                ('BloggerAc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloggerAc', to='Bloggers.blogger')),
                ('Dislikes', models.ManyToManyField(blank=True, related_name='blogpostdislike', to=settings.AUTH_USER_MODEL)),
                ('Uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloguploader', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='blogpostLikes', to=settings.AUTH_USER_MODEL)),
                ('save_readlater', models.ManyToManyField(blank=True, related_name='blogpostreadlater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created', '-modified'),
            },
        ),
        migrations.CreateModel(
            name='searched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(editable=False, max_length=40, null=True)),
                ('SearchQ', models.CharField(max_length=600)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('USER', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.CharField(max_length=160)),
                ('Commentfrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Commentfrom', to=settings.AUTH_USER_MODEL)),
                ('Commenton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Commenton', to='BlogPost.blog')),
            ],
        ),
    ]
