# Generated by Django 3.1.4 on 2021-03-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Que', models.CharField(max_length=9999)),
                ('Ans', models.CharField(blank=True, max_length=999999, null=True)),
                ('Ans_Blog', models.TextField(blank=True, null=True)),
                ('Quetype', models.CharField(blank=True, choices=[('blogster-terminology', 'blogster terminology'), ('how_to', 'how to'), ('about-Blogster', 'about Blogster'), ('technical_que', 'technical que'), ('Blogging', 'Blogging')], default='Personal-Blogs', max_length=100)),
            ],
        ),
    ]
