# Generated by Django 3.1.7 on 2021-03-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Que', models.CharField(max_length=9999)),
                ('ShortAns', models.TextField(blank=True, null=True)),
                ('LongAns', models.TextField(blank=True, null=True)),
                ('Quetype', models.CharField(blank=True, choices=[('blogster-terminology', 'blogster terminology'), ('how_to', 'how to'), ('about-Blogster', 'about Blogster'), ('technical_que', 'technical que'), ('Blogging', 'Blogging')], default='about-Blogster', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HelpCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=1000)),
                ('Group', models.CharField(choices=[('Getting_Started', 'Getting Started'), ('Login', 'Login'), ('Account_settings', 'Account settings'), ('navigating', 'navigating'), ('Managing_blogs', 'Managing blogs'), ('Terms_&_policies', 'Terms & policies'), ('Others', 'Others')], default='Others', max_length=100)),
                ('articalname', models.CharField(max_length=9999)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
