# Generated by Django 3.1.4 on 2021-03-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infodata', '0002_helpcenter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helpcenter',
            old_name='subject',
            new_name='subject_name',
        ),
        migrations.AddField(
            model_name='helpcenter',
            name='Group',
            field=models.CharField(blank=True, choices=[('Getting_Started', 'Getting Started'), ('Login', 'Login'), ('Account_settings', 'Account settings'), ('navigating', 'navigating'), ('Managing_blogs', 'Managing blogs'), ('Terms_&_policies', 'Terms & policies'), ('Others', 'Others')], default='Others', max_length=100),
        ),
    ]
