# Generated by Django 3.1.4 on 2021-03-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infodata', '0003_auto_20210307_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpcenter',
            name='Group',
            field=models.CharField(choices=[('Getting_Started', 'Getting Started'), ('Login', 'Login'), ('Account_settings', 'Account settings'), ('navigating', 'navigating'), ('Managing_blogs', 'Managing blogs'), ('Terms_&_policies', 'Terms & policies'), ('Others', 'Others')], default='Others', max_length=100),
        ),
    ]
