# Generated by Django 3.1.4 on 2021-03-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infodata', '0004_auto_20210315_0641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqs',
            old_name='Ans_Blog',
            new_name='Long_Ans',
        ),
        migrations.RemoveField(
            model_name='faqs',
            name='Ans',
        ),
        migrations.AddField(
            model_name='faqs',
            name='Short_Ans',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='Quetype',
            field=models.CharField(blank=True, choices=[('blogster-terminology', 'blogster terminology'), ('how_to', 'how to'), ('about-Blogster', 'about Blogster'), ('technical_que', 'technical que'), ('Blogging', 'Blogging')], default='about-Blogster', max_length=100),
        ),
    ]
